### ISSUE TITLE
Why use -cost get the record of bigger latency?

### ISSUE THREAD

**Issue by yogurfrul** [awslabs/lorien#1]
We know the cost in auto_schedule measure result means **[latency]** or **[Cost]**， the smaller the better.
While in the code as below:
https://github.com/awslabs/lorien/blob/bcd39132e5f0738ee6f4685676ea8628cb4cea1b/lorien/dialect/tvm_dial/auto_scheduler_dial/result.py#L81
 as you say `eapq is min-heap `   the record on the top would be the best. 
Why use -cost get the record of bigger latency?

**Comment by yogurfrul** [comment]
@comaniac

**Comment by comaniac** [comment]
The heap aims to keep the top-N records with minimum cost. To do so, we iterate all records and push them to the heap. When the heap size is larger than N, we remove the one with worst cost. Thus, we need max-heap to keep the so far worst record on the top in O(1).

**Comment by yogurfrul** [comment]
Yes, I got the use of heap . 
While  I found the func `records.peak()` in tutorials to get the best schedule, actually it retuen the first record. 
As you say above, the heap aims to keep the worst record on the top.
And I run the test with my own record of the same workload, the peak func really get the the first one in _data with worse cost.
